{
    "Title":"Crouching Tiger, Hidden Dragon",
    "Year":"2000",
    "Rated":"PG-13",
    "Released":"12 Jan 2001",
    "Runtime":"120 min",
    "Genre":"Action, Adventure, Fantasy",
    "Director":"Ang Lee",
    "Writer":"Du Lu Wang (book), Hui-Ling Wang (screenplay), James Schamus (screenplay), Kuo Jung Tsai (screenplay)",
    "Actors":"Yun-Fat Chow, Michelle Yeoh, Ziyi Zhang, Chen Chang",
    "Plot":"In 19th century Qing Dynasty China, a warrior gives his sword, Green Destiny, to his lover to deliver to safe keeping, but it is stolen, and the chase is on to find it. The search leads to the House of Yu where the story takes on a whole different level.",
    "Language":"Mandarin",
    "Country":"Taiwan, Hong Kong, USA, China",
    "Awards":"Won 4 Oscars. Another 96 wins & 128 nominations.",
    "Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNDdhMzMxOTctNDMyNS00NTZmLTljNWEtNTc4MDBmZTYxY2NmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    "Ratings":[
                {"Source":"Internet Movie Database","Value":"7.9/10"},
                {"Source":"Rotten Tomatoes","Value":"97%"},
                {"Source":"Metacritic","Value":"93/100"}
            ],
    "Metascore":"93",
    "imdbRating":"7.9",
    "imdbVotes":"224,566",
    "imdbID":"tt0190332",
    "Type":"movie",
    "DVD":"05 Jun 2001",
    "BoxOffice":"N/A",
    "Production":"Sony Pictures Classics",
    "Website":"http://www.crouchingtiger.com",
    "Response":"True"
}